// GENERATED by tools/lunarlockout_levels.py (deterministic, seed 58) — do not hand-edit.
//
// Every OptimalMoves below is an exhaustive-BFS result, not a hand-authored guess, and
// LunarLockoutOracleTests re-derives all of them through the .pg oracle as a cross-check.
//
// The level pack inherited from the WebGames port was unusable (13 of 15 grids had no legal first
// move at all), so the ladder is authored here instead. See docs/prd/WEBGAMES_RETIREMENT_PRD.md §5.3.

namespace MintPlayer.AI.ReinforcementLearning.Environments.LunarLockout;

/// <summary>One Lunar Lockout puzzle: a 5x5 grid plus its BFS-proven minimum move count.</summary>
/// <param name="Name">Display name.</param>
/// <param name="Grid">Five rows, top row first. <c>R</c> = target robot, <c>.</c> = empty, any other letter = helper.</param>
/// <param name="OptimalMoves">Exhaustively verified minimum number of slides to bring <c>R</c> to the centre.</param>
public sealed record LunarLockoutLevel(string Name, string[] Grid, int OptimalMoves);

/// <summary>The shipped Lunar Lockout ladder, held out of training and used as the gate set (PRD D4).</summary>
public static class LunarLockoutLevels
{
    public static readonly LunarLockoutLevel[] All =
    [
        new("Level 1", [".....", "B.G..", ".....", "..R..", "....."], 1),
        new("Level 2", [".....", ".....", "R.B.G", ".....", "....."], 2),
        new("Level 3", [".R.B.", ".....", ".....", ".G.Y.", "....."], 3),
        new("Level 4", [".B...", "...G.", ".....", ".R.Y.", "....."], 4),
        new("Level 5", [".....", "B.R.G", ".....", ".....", ".Y.P."], 5),
        new("Level 6", ["B....", "....G", "R....", "....Y", "P...."], 6),
        new("Level 7", [".B.G.", ".....", ".R...", ".....", ".Y.P."], 7),
        new("Level 8", [".B...", "....R", ".G...", ".....", ".Y..P"], 8),
        new("Level 9", [".B..G", ".....", "....Y", ".R...", "....P"], 9),
        new("Level 10", [".BG.Y", ".....", ".....", ".....", ".R..P"], 10),
        new("Level 11", ["B..R.", ".....", ".....", ".....", "G.Y.P"], 11),
        new("Level 12", ["B....", "....R", "G....", ".....", "Y..P."], 12),
    ];
}
