using System.Text.Json;
using RLNet.Environments;

namespace RLNet.Tests;

public class CartPoleTests
{
    [Fact]
    public void GoldenTrajectories_MatchGymnasiumReference()
    {
        // Fixture generated by tools/generate_goldens.py against gymnasium 1.3.0.
        // Any transcription error in the physics constants or update order shows up here.
        var path = Path.Combine(AppContext.BaseDirectory, "Fixtures", "cartpole_golden.json");
        using var fixture = JsonDocument.Parse(File.ReadAllText(path));

        foreach (var scenario in fixture.RootElement.GetProperty("scenarios").EnumerateArray())
        {
            string name = scenario.GetProperty("name").GetString()!;
            var initial = scenario.GetProperty("initial_state").EnumerateArray().Select(e => e.GetDouble()).ToArray();

            var env = new CartPoleEnv();
            env.Reset(0);
            env.SetState(initial[0], initial[1], initial[2], initial[3]);

            int t = 0;
            foreach (var step in scenario.GetProperty("steps").EnumerateArray())
            {
                var result = env.Step(step.GetProperty("action").GetInt32());
                var expectedObs = step.GetProperty("obs").EnumerateArray().Select(e => e.GetSingle()).ToArray();

                for (int i = 0; i < 4; i++)
                    Assert.True(
                        Math.Abs(result.Observation[i] - expectedObs[i]) < 1e-5f,
                        $"{name} step {t}, obs[{i}]: expected {expectedObs[i]}, got {result.Observation[i]}");
                Assert.Equal(step.GetProperty("reward").GetDouble(), result.Reward);
                Assert.Equal(step.GetProperty("terminated").GetBoolean(), result.Terminated);
                Assert.Equal(step.GetProperty("truncated").GetBoolean(), result.Truncated);
                t++;
            }
        }
    }

    [Fact]
    public void Reset_InitializesAllComponentsWithinPlusMinus005()
    {
        var env = new CartPoleEnv();
        for (ulong seed = 0; seed < 50; seed++)
        {
            var (obs, _) = env.Reset(seed);
            Assert.All(obs, v => Assert.InRange(v, -0.05f, 0.05f));
        }
    }

    [Fact]
    public void RewardIsOneEveryStep_IncludingTheTerminalStep()
    {
        var env = new CartPoleEnv();
        env.Reset(3);
        env.SetState(0, 0, 0.20, 1.0); // about to tip past 12°

        var step = env.Step(1);
        Assert.True(step.Terminated);
        Assert.Equal(1.0, step.Reward); // Gymnasium pays the terminal step too
    }

    [Fact]
    public void TerminationAngle_Is12Degrees_NotTheObservationBound()
    {
        var env = new CartPoleEnv();
        env.Reset(3);

        // theta stays at 0.205 rad after one step from standstill (position updates use
        // the old, zero velocity) — inside the 0.2095 rad termination threshold.
        env.SetState(0, 0, 0.205, 0);
        Assert.False(env.Step(1).Terminated);

        // 0.215 rad is past 12° but well inside the 0.418 rad observation bound: terminal.
        env.SetState(0, 0, 0.215, 0);
        Assert.True(env.Step(1).Terminated);
    }

    [Fact]
    public void TruncatesAtExactly500Steps_UnderBalancingController()
    {
        var env = new CartPoleEnv();
        var (obs, _) = env.Reset(3);

        int steps = 0;
        while (true)
        {
            // PD controller on the pole angle: easily balances for the full episode.
            int action = obs[2] + 0.5f * obs[3] > 0 ? 1 : 0;
            var result = env.Step(action);
            obs = result.Observation;
            steps++;

            if (result.Done)
            {
                Assert.True(result.Truncated, $"controller fell over at step {steps}");
                Assert.False(result.Terminated);
                Assert.Equal(500, steps);
                break;
            }
        }
    }
}
