using System.Reflection;
using System.Text.Json;

namespace MintPlayer.AI.ReinforcementLearning.Environments.LevelPacks;

/// <summary>One level in an embedded pack: a name, an ASCII grid, and an optional verified optimal move count.</summary>
/// <param name="Name">Display name.</param>
/// <param name="Grid">Grid rows, TOP row first.</param>
/// <param name="OptimalMoves">Exhaustively verified minimum move count, or <c>null</c> when the board is beyond
/// any exact solver (which is the normal case for the larger Block Dude levels).</param>
public sealed record LevelPackEntry(string Name, string[] Grid, int? OptimalMoves);

/// <summary>
/// Reads a level pack from this assembly's embedded resources.
/// </summary>
/// <remarks>
/// The JSON files under <c>&lt;Game&gt;/levels/</c> are the single source of truth for level content: embedded
/// here for training (campaign, Lab, tests) and linked into <c>RLDemo.Web/wwwroot/levels</c> so the Angular app
/// fetches the identical bytes. They are generated by <c>tools/blockdude_levels.py</c> and
/// <c>tools/lunarlockout_levels.py</c> — never hand-edited.
/// </remarks>
public static class EmbeddedLevelPack
{
    private sealed record PackDocument(int Version, PackLevel[] Levels);

    private sealed record PackLevel(string Name, string[] Grid, int? OptimalMoves);

    private static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);

    /// <summary>Loads the pack whose embedded resource name ends with <paramref name="fileName"/>.</summary>
    /// <exception cref="InvalidOperationException">The resource is missing, empty, or malformed — all of which
    /// mean a broken build rather than a recoverable runtime condition.</exception>
    public static LevelPackEntry[] Load(string fileName)
    {
        var assembly = typeof(EmbeddedLevelPack).Assembly;

        // Matched by suffix rather than by a hard-coded resource name: MSBuild derives those from the root
        // namespace plus the directory path, so a folder rename would otherwise break this silently.
        string resource = Array.Find(assembly.GetManifestResourceNames(),
                              n => n.EndsWith(fileName, StringComparison.Ordinal))
                          ?? throw new InvalidOperationException(
                              $"Embedded level pack '{fileName}' is missing. Known resources: " +
                              string.Join(", ", assembly.GetManifestResourceNames()));

        using var stream = assembly.GetManifestResourceStream(resource)
                           ?? throw new InvalidOperationException($"Embedded level pack '{resource}' could not be opened.");

        var document = JsonSerializer.Deserialize<PackDocument>(stream, Json)
                       ?? throw new InvalidOperationException($"Embedded level pack '{resource}' is not valid JSON.");

        if (document.Levels is null || document.Levels.Length == 0)
            throw new InvalidOperationException($"Embedded level pack '{resource}' contains no levels.");

        var entries = new LevelPackEntry[document.Levels.Length];
        for (int i = 0; i < document.Levels.Length; i++)
        {
            var level = document.Levels[i];
            if (string.IsNullOrWhiteSpace(level.Name))
                throw new InvalidOperationException($"'{resource}' level {i} has no name.");
            if (level.Grid is null || level.Grid.Length == 0)
                throw new InvalidOperationException($"'{resource}' level '{level.Name}' has an empty grid.");

            int width = level.Grid[0].Length;
            foreach (string row in level.Grid)
                if (row.Length != width)
                    throw new InvalidOperationException(
                        $"'{resource}' level '{level.Name}' is ragged: expected rows of {width} cells.");

            entries[i] = new LevelPackEntry(level.Name, level.Grid, level.OptimalMoves);
        }
        return entries;
    }

    /// <summary>Reads the raw JSON of an embedded pack, for byte-level comparison against the copy the web app serves.</summary>
    public static string ReadRaw(string fileName)
    {
        var assembly = typeof(EmbeddedLevelPack).Assembly;
        string resource = Array.Find(assembly.GetManifestResourceNames(),
                              n => n.EndsWith(fileName, StringComparison.Ordinal))
                          ?? throw new InvalidOperationException($"Embedded level pack '{fileName}' is missing.");
        using var stream = assembly.GetManifestResourceStream(resource)!;
        using var reader = new StreamReader(stream);
        return reader.ReadToEnd();
    }
}
