using MintPlayer.AI.ReinforcementLearning.Environments.LunarLockout;

namespace MintPlayer.AI.ReinforcementLearning.Tests;

/// <summary>
/// Exact-oracle conformance, and the M58.1 gate: every shipped level's stored move count is re-derived by the
/// .pg oracle. The ladder is generated by <c>tools/lunarlockout_levels.py</c>, whose rules are implemented
/// independently of the engine — so these tests are a genuine cross-check of two implementations, which is how
/// the inherited WebGames level pack was caught as unplayable (PRD §5.3).
/// </summary>
public class LunarLockoutOracleTests
{
    private static LunarLockoutBoard Board(params string[] rows) => LunarLockoutBoard.FromGrid(rows);

    [Fact]
    public void EveryShippedLevel_IsSolvable_AndMatchesItsStoredOptimal()
    {
        var mismatches = new List<string>();
        var unsolvable = new List<string>();

        foreach (var level in LunarLockoutLevels.All)
        {
            var oracle = new LunarLockoutOracle(Board(level.Grid));
            Assert.False(oracle.Truncated, $"'{level.Name}': a 5x5 board must never exceed the oracle cap.");

            Assert.True(level.OptimalMoves.HasValue,
                $"'{level.Name}': the Lunar Lockout pack must carry a verified optimal move count.");

            int optimal = oracle.OptimalFromStart;
            if (optimal < 0) unsolvable.Add(level.Name);
            else if (optimal != level.OptimalMoves!.Value)
                mismatches.Add($"'{level.Name}': stored {level.OptimalMoves}, BFS-optimal {optimal}");
        }

        Assert.True(
            unsolvable.Count == 0 && mismatches.Count == 0,
            $"Unsolvable: {(unsolvable.Count == 0 ? "none" : string.Join(", ", unsolvable))}. " +
            $"Mismatched: {(mismatches.Count == 0 ? "none" : string.Join(" | ", mismatches))}.");
    }

    [Fact]
    public void TheLadderRampsInDifficulty_AndHasNoDuplicatePositions()
    {
        // A ladder whose rungs are out of order, or that ships the same position twice, is a content bug the
        // generator is supposed to prevent.
        var levels = LunarLockoutLevels.All;
        Assert.NotEmpty(levels);

        for (int i = 1; i < levels.Length; i++)
            Assert.True(levels[i].OptimalMoves!.Value > levels[i - 1].OptimalMoves!.Value,
                $"'{levels[i].Name}' ({levels[i].OptimalMoves}) does not exceed '{levels[i - 1].Name}' ({levels[i - 1].OptimalMoves}).");

        var keys = levels.Select(l => Board(l.Grid).Key).ToList();
        Assert.Equal(keys.Count, keys.Distinct().Count());
    }

    [Fact]
    public void FollowingOptimalActions_ReachesTheGoalInExactlyTheLabelledDistance()
    {
        // The label set must be internally consistent: every optimal action drops the distance by exactly one, so
        // greedily following any of them solves the board in `dist` moves.
        foreach (var level in LunarLockoutLevels.All)
        {
            var start = Board(level.Grid);
            var oracle = new LunarLockoutOracle(start);
            int expected = oracle.OptimalFromStart;
            if (expected < 0) continue;

            var cur = start;
            int moves = 0;
            while (!cur.IsSolved)
            {
                int mask = oracle.OptimalActionsOf(cur);
                Assert.NotEqual(0, mask);

                int action = -1;
                for (int a = 0; a < cur.ActionCount; a++)
                    if ((mask & (1 << a)) != 0) { action = a; break; }

                int before = oracle.DistanceOf(cur);
                cur = cur.Apply(action);
                Assert.Equal(before - 1, oracle.DistanceOf(cur));

                moves++;
                Assert.True(moves <= expected, $"'{level.Name}': optimal play overran {expected} moves.");
            }
            Assert.Equal(expected, moves);
        }
    }

    [Fact]
    public void SolvedStatesAreLabelledZero_AndOptimalMasksOnlyNameLegalActions()
    {
        foreach (var level in LunarLockoutLevels.All)
        {
            var start = Board(level.Grid);
            var oracle = new LunarLockoutOracle(start);
            if (oracle.OptimalFromStart < 0) continue;

            int mask = oracle.OptimalActionsOf(start);
            for (int a = 0; a < start.ActionCount; a++)
                if ((mask & (1 << a)) != 0)
                    Assert.True(start.IsLegal(a), $"'{level.Name}': optimal mask names illegal action {a}.");
        }
    }

    [Fact]
    public void AnAlreadySolvedBoard_IsDistanceZero()
    {
        var solved = Board(
            ".....",
            ".....",
            "..RB.",
            ".....",
            ".....");

        Assert.True(solved.IsSolved);
        Assert.Equal(0, new LunarLockoutOracle(solved).OptimalFromStart);
    }

    [Fact]
    public void AnUnsolvableBoard_ReportsMinusOne()
    {
        // Two robots in a row can only ever slide against each other along that row; the target can never reach
        // the centre, so the oracle must report unsolvable rather than truncating or throwing.
        var board = Board(
            "R...B",
            ".....",
            ".....",
            ".....",
            ".....");

        var oracle = new LunarLockoutOracle(board);
        Assert.False(oracle.Truncated);
        Assert.Equal(-1, oracle.OptimalFromStart);
    }

    [Fact]
    public void Oracle_ReportsTruncation_RatherThanSilentlyProducingNoLabels()
    {
        // A cap of 1 state cannot even hold the start position's successors. Truncated must be set and the label
        // arrays emptied, so a caller can log a rejection instead of mistaking it for "no labels here".
        var oracle = new LunarLockoutOracle(Board(LunarLockoutLevels.All[^1].Grid), maxStates: 1);

        Assert.True(oracle.Truncated);
        Assert.Equal(0, oracle.StateCount);
        Assert.Equal(-1, oracle.OptimalFromStart);
    }
}
