// <auto-generated> Transpiled from fruitcake_solver.pg by MintPlayer.Polyglot 0.1.1. DO NOT EDIT.
// Regenerate on Windows: polyglot build fruitcake_solver.pg --out .
#nullable disable
abstract record Option<T>;
sealed record Some<T>(T value) : Option<T>;
sealed record None<T>() : Option<T>;
record PgFruitDef(double radiusPx, int mergePoints);
record PgContact(PgFruitBody a, PgFruitBody b, double nx, double ny, double pen);
class PgFruitBody
{
    public double x;
    public double y;
    public double vx;
    public double vy;
    public double angle;
    public double angularVel;
    public double r;
    public int tier;
    public double invMass;
    public double invI;
    public bool pendingMerge;
    public bool removed;
    public PgFruitBody(double x, double y, double r, int tier, double invMass, double invI)
    {
        this.x = x;
        this.y = y;
        this.r = r;
        this.tier = tier;
        this.invMass = invMass;
        this.invI = invI;
        this.vx = 0.0;
        this.vy = 0.0;
        this.angle = 0.0;
        this.angularVel = 0.0;
        this.pendingMerge = false;
        this.removed = false;
    }
    public double speed => global::System.Math.Sqrt(this.vx * this.vx + this.vy * this.vy);
}
class PgFruitCakeWorld
{
    public static readonly double Width = 620.0;
    public static readonly double Height = 850.0;
    public static readonly double DangerLineY = 150.0;
    public static readonly double Gravity = 9.8 * 64.0;
    public static readonly double Restitution = 0.1;
    public static readonly double Friction = 0.3;
    public static readonly double RestitutionThresholdPx = 64.0;
    public static readonly int VelocityIterations = 12;
    public static readonly int PositionIterations = 4;
    public static readonly double Slop = 0.5;
    public static readonly double CorrectionPercent = 0.8;
    public static readonly double AngularDamping = 0.995;
    public readonly bool rotation;
    public global::System.Collections.Generic.List<PgFruitBody> bodies = new global::System.Collections.Generic.List<PgFruitBody>();
    public global::System.Collections.Generic.List<(PgFruitBody, PgFruitBody)> mergeQueue = new global::System.Collections.Generic.List<(PgFruitBody, PgFruitBody)>();
    public global::System.Collections.Generic.List<PgContact> contacts = new global::System.Collections.Generic.List<PgContact>();
    public PgFruitCakeWorld(bool enableRotation = false)
    {
        this.rotation = enableRotation;
    }
    public int count => this.bodies.Count;
    public PgFruitBody spawnFruit(int tier, double xPx, double yPx)
    {
        var def = PolyglotProgram.byTier(tier);
        var r = def.radiusPx;
        var mass = global::System.Math.PI * r * r;
        var inertia = 0.5 * mass * r * r;
        var body = new PgFruitBody(xPx, yPx, r, tier, 1.0 / mass, (this.rotation ? 1.0 / inertia : 0.0));
        this.bodies.Add(body);
        return body;
    }
    public void clear()
    {
        this.bodies.Clear();
        this.mergeQueue.Clear();
    }
    public int step(double dt)
    {
        foreach (var b in this.bodies)
        {
            b.vy += PgFruitCakeWorld.Gravity * dt;
        }
        this.buildContacts(true);
        for (var _it = 0; _it < PgFruitCakeWorld.VelocityIterations; _it++)
        {
            foreach (var c in this.contacts)
            {
                PgFruitCakeWorld.resolveVelocity(c);
            }
        }
        foreach (var b in this.bodies)
        {
            b.x += b.vx * dt;
            b.y += b.vy * dt;
            if (this.rotation)
            {
                b.angle += b.angularVel * dt;
                b.angularVel *= PgFruitCakeWorld.AngularDamping;
            }
        }
        for (var _it = 0; _it < PgFruitCakeWorld.PositionIterations; _it++)
        {
            this.buildContacts(false);
            foreach (var c in this.contacts)
            {
                PgFruitCakeWorld.correctPosition(c);
            }
        }
        return this.flushMerges();
    }
    public double maxSpeed()
    {
        var m = 0.0;
        foreach (var b in this.bodies)
        {
            m = global::System.Math.Max(m, b.speed);
        }
        return m;
    }
    public int settleAfterDrop(double settleSpeedPx, int minSubsteps, int maxSubsteps, double dt = 1.0 / 60.0)
    {
        var points = 0;
        for (var sub = 0; sub < maxSubsteps; sub++)
        {
            var gained = this.step(dt);
            points += gained;
            if (sub >= minSubsteps && gained == 0 && this.maxSpeed() < settleSpeedPx)
            {
                break;
            }
        }
        return points;
    }
    public double pileHeight()
    {
        var minTop = PgFruitCakeWorld.Height;
        foreach (var b in this.bodies)
        {
            minTop = global::System.Math.Min(minTop, b.y - b.r);
        }
        return PgFruitCakeWorld.Height - minTop;
    }
    public bool anyEjected()
    {
        foreach (var b in this.bodies)
        {
            if (b.y - b.r > PgFruitCakeWorld.Height || b.x < 0.0 - b.r || b.x > PgFruitCakeWorld.Width + b.r)
            {
                return true;
            }
        }
        return false;
    }
    public bool anyRestingAboveDangerLine(double restSpeedPx)
    {
        foreach (var b in this.bodies)
        {
            if (b.y < PgFruitCakeWorld.DangerLineY && b.speed < restSpeedPx)
            {
                return true;
            }
        }
        return false;
    }
    public void buildContacts(bool detect)
    {
        this.contacts.Clear();
        foreach (var b in this.bodies)
        {
            var left = b.r - b.x;
            if (left > 0.0)
            {
                this.contacts.Add(new PgContact(b, null, -1.0, 0.0, left));
            }
            var right = b.x + b.r - PgFruitCakeWorld.Width;
            if (right > 0.0)
            {
                this.contacts.Add(new PgContact(b, null, 1.0, 0.0, right));
            }
            var floor = b.y + b.r - PgFruitCakeWorld.Height;
            if (floor > 0.0)
            {
                this.contacts.Add(new PgContact(b, null, 0.0, 1.0, floor));
            }
        }
        for (var i = 0; i < this.bodies.Count; i++)
        {
            var a = this.bodies[i];
            for (var j = i + 1; j < this.bodies.Count; j++)
            {
                var b = this.bodies[j];
                var dx = b.x - a.x;
                var dy = b.y - a.y;
                var rsum = a.r + b.r;
                var d2 = dx * dx + dy * dy;
                if (d2 >= rsum * rsum)
                {
                    continue;
                }
                var d = global::System.Math.Sqrt(d2);
                if (d == 0.0)
                {
                    d = 0.0001;
                }
                if (detect && a.tier == b.tier && !a.pendingMerge && !b.pendingMerge)
                {
                    a.pendingMerge = true;
                    b.pendingMerge = true;
                    this.mergeQueue.Add((a, b));
                    continue;
                }
                this.contacts.Add(new PgContact(a, b, dx / d, dy / d, rsum - d));
            }
        }
    }
    public static void resolveVelocity(PgContact c)
    {
        var a = c.a;
        var b = c.b;
        var nx = c.nx;
        var ny = c.ny;
        var invMa = a.invMass;
        var invMb = b?.invMass ?? 0.0;
        var invIa = a.invI;
        var invIb = b?.invI ?? 0.0;
        if (invMa + invMb == 0.0)
        {
            return;
        }
        var rax = a.r * nx;
        var ray = a.r * ny;
        var rbx = (b == null ? 0.0 : -((PgFruitBody)(b)).r * nx);
        var rby = (b == null ? 0.0 : -((PgFruitBody)(b)).r * ny);
        var wa = a.angularVel;
        var wb = b?.angularVel ?? 0.0;
        var rvx = (b == null ? 0.0 : ((PgFruitBody)(b)).vx - wb * rby) - (a.vx - wa * ray);
        var rvy = (b == null ? 0.0 : ((PgFruitBody)(b)).vy + wb * rbx) - (a.vy + wa * rax);
        var relN = rvx * nx + rvy * ny;
        if (relN > 0.0)
        {
            return;
        }
        var e = (relN < -PgFruitCakeWorld.RestitutionThresholdPx ? PgFruitCakeWorld.Restitution : 0.0);
        var rnA = rax * ny - ray * nx;
        var rnB = rbx * ny - rby * nx;
        var kn = invMa + invMb + invIa * rnA * rnA + invIb * rnB * rnB;
        if (kn <= 0.0)
        {
            return;
        }
        var jn = -(1.0 + e) * relN / kn;
        PgFruitCakeWorld.applyImpulse(a, b, rax, ray, rbx, rby, jn * nx, jn * ny);
        var wa2 = a.angularVel;
        var wb2 = b?.angularVel ?? 0.0;
        rvx = (b == null ? 0.0 : ((PgFruitBody)(b)).vx - wb2 * rby) - (a.vx - wa2 * ray);
        rvy = (b == null ? 0.0 : ((PgFruitBody)(b)).vy + wb2 * rbx) - (a.vy + wa2 * rax);
        var rvn = rvx * nx + rvy * ny;
        var tx = rvx - rvn * nx;
        var ty = rvy - rvn * ny;
        var tlen = global::System.Math.Sqrt(tx * tx + ty * ty);
        if (tlen < 0.000001)
        {
            return;
        }
        tx /= tlen;
        ty /= tlen;
        var rtA = rax * ty - ray * tx;
        var rtB = rbx * ty - rby * tx;
        var kt = invMa + invMb + invIa * rtA * rtA + invIb * rtB * rtB;
        if (kt <= 0.0)
        {
            return;
        }
        var jt = -(rvx * tx + rvy * ty) / kt;
        var maxJt = PgFruitCakeWorld.Friction * jn;
        jt = global::System.Math.Min(maxJt, global::System.Math.Max(-maxJt, jt));
        PgFruitCakeWorld.applyImpulse(a, b, rax, ray, rbx, rby, jt * tx, jt * ty);
    }
    public static void applyImpulse(PgFruitBody a, PgFruitBody b, double rax, double ray, double rbx, double rby, double jx, double jy)
    {
        a.vx -= a.invMass * jx;
        a.vy -= a.invMass * jy;
        a.angularVel -= a.invI * (rax * jy - ray * jx);
        if (b != null)
        {
            ((PgFruitBody)(b)).vx += ((PgFruitBody)(b)).invMass * jx;
            ((PgFruitBody)(b)).vy += ((PgFruitBody)(b)).invMass * jy;
            ((PgFruitBody)(b)).angularVel += ((PgFruitBody)(b)).invI * (rbx * jy - rby * jx);
        }
    }
    public static void correctPosition(PgContact c)
    {
        var a = c.a;
        var b = c.b;
        var invSum = a.invMass + (b?.invMass ?? 0.0);
        if (invSum == 0.0)
        {
            return;
        }
        var corr = global::System.Math.Max(c.pen - PgFruitCakeWorld.Slop, 0.0) / invSum * PgFruitCakeWorld.CorrectionPercent;
        a.x -= a.invMass * corr * c.nx;
        a.y -= a.invMass * corr * c.ny;
        if (b != null)
        {
            ((PgFruitBody)(b)).x += ((PgFruitBody)(b)).invMass * corr * c.nx;
            ((PgFruitBody)(b)).y += ((PgFruitBody)(b)).invMass * corr * c.ny;
        }
    }
    public int flushMerges()
    {
        var points = 0;
        var removed = false;
        foreach (var (a, b) in this.mergeQueue)
        {
            if (a.removed || b.removed)
            {
                continue;
            }
            a.removed = true;
            b.removed = true;
            removed = true;
            var tier = a.tier;
            var cx = (a.x + b.x) * 0.5;
            var cy = (a.y + b.y) * 0.5;
            var rt = PolyglotProgram.mergeResultTier(tier);
            if (rt != null)
            {
                this.spawnFruit((int)(rt), cx, cy);
            }
            points += PolyglotProgram.byTier(tier).mergePoints;
        }
        this.mergeQueue.Clear();
        if (removed)
        {
            this.bodies.RemoveAll((b) => b.removed);
        }
        return points;
    }
}

static class PolyglotProgram
{
    static readonly global::System.Collections.Generic.List<PgFruitDef> Catalog = new global::System.Collections.Generic.List<PgFruitDef> { new PgFruitDef(24.0, 1), new PgFruitDef(32.0, 3), new PgFruitDef(40.0, 6), new PgFruitDef(56.0, 10), new PgFruitDef(64.0, 15), new PgFruitDef(72.0, 21), new PgFruitDef(84.0, 28), new PgFruitDef(96.0, 36), new PgFruitDef(128.0, 45), new PgFruitDef(160.0, 55), new PgFruitDef(192.0, 66) };
    public static PgFruitDef byTier(int tier)
    {
        return Catalog[tier - 1];
    }
    public static int? mergeResultTier(int tier)
    {
        return (tier < Catalog.Count ? tier + 1 : null);
    }
}
