using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using MintPlayer.AI.ReinforcementLearning.Core;            // generated AddReinforcementLearningCore()
using MintPlayer.AI.ReinforcementLearning.Core.Checkpoints;

namespace MintPlayer.AI.ReinforcementLearning.Hosting;

/// <summary>
/// Host-builder for reinforcement-learning training apps — the AI counterpart to
/// <c>WebApplication.CreateBuilder</c>. Returns a <see cref="HostApplicationBuilder"/> preconfigured with
/// the default configuration sources (appsettings.json + environment) and console logging, plus the RL runtime
/// services (model store, system clock, <c>CampaignRunner</c>), so Lab/Console training tools compose with
/// dependency injection all the way down. Add the GPU compute backend with the Ilgpu.Hosting package's
/// <c>services.AddGpuBackend()</c> on the returned builder.
/// </summary>
public static class AIHost
{
    /// <summary>Create a host builder whose model store reads/writes under <paramref name="dataDirectory"/>.</summary>
    public static HostApplicationBuilder CreateBuilder(string dataDirectory)
    {
        ArgumentNullException.ThrowIfNull(dataDirectory);
        var builder = Host.CreateApplicationBuilder();
        builder.Services.AddReinforcementLearning(dataDirectory);
        return builder;
    }
}

/// <summary>Dependency-injection registration for the reinforcement-learning runtime services.</summary>
public static class ReinforcementLearningServiceCollectionExtensions
{
    /// <summary>
    /// Registers the model store (a <see cref="FileModelStore"/> over <paramref name="dataDirectory"/>), the
    /// system <see cref="TimeProvider"/>, and (via the Core source-generated registration) the campaign runner.
    /// </summary>
    public static IServiceCollection AddReinforcementLearning(this IServiceCollection services, string dataDirectory)
    {
        services.AddSingleton(TimeProvider.System);
        services.AddSingleton<IModelStore>(_ => new FileModelStore(dataDirectory));
        services.AddReinforcementLearningCore(); // generated by MintPlayer.SourceGenerators — registers CampaignRunner
        return services;
    }
}
